## Projektbeschreibung
Im Rahmen dieses Projekts wurden die im Abschnitt „Dental Indicators“ der Weltgesundheitsorganisation (WHO) veröffentlichten Datensätze im CSV‑Format untersucht.
Nach der Analyse wurden die für die Studie geeigneten Datensätze ausgewählt und anhand der relevanten Variablen zusammengeführt.

Durch die Kombination verschiedener Datensätze wurde eine aussagekräftigere, nutzbare und ganzheitliche Datenstruktur für die Analyse erstellt.

In [1]:
import pandas as pd
import os

In [2]:
print(os.getcwd())

C:\Users\User Laptop\Desktop\Projekt_\projekt_dental\notebooks

In [3]:
df1 = pd.read_excel("../data/raw_data/dental_healthcarei_inMillion_total_expenditure.xlsx")
df2 = pd.read_excel("../data/raw_data/number_of_labour_days_needed_to_buy_annual_support_of_fluoride_tootthpaste_perPerson.xlsx")
df3 = pd.read_excel("../data/raw_data/perCapita_expenditure_on_dentalhealth.xlsx")
df4 = pd.read_excel("../data/raw_data/prevalence_of_edentulism_in_people20+.xlsx")
df5 = pd.read_excel("../data/raw_data/prevalence_of_severe_peridontal_disease_in_people15+.xlsx")
df6 = pd.read_excel("../data/raw_data/Prevalence_of_untreated_caries_of_permanenet_teetf_5+.xlsx")
df7 = pd.read_excel("../data/raw_data/urgent_treatment_for_providing_emergency_oral_care_pain.xlsx")

In [4]:
df8 = pd.read_excel("../data/raw_data/affordability_of_fluoride_toothpaste.xlsx")
df9 = pd.read_excel("../data/raw_data/dental_assistants_therapists_num.xlsx")
df10 = pd.read_excel("../data/raw_data/dental_prosthetic_technicians_per10000popul.xlsx")
df11 = pd.read_excel("../data/raw_data/dentists_per_10000population.xlsx")
df12 = pd.read_excel("../data/raw_data/lip_and_oral_cavity_cancer2020.xlsx")
df13 = pd.read_excel("../data/raw_data/prevelence_of_untreated_caries_of_deciduous_teeth_in_children_1_9.xlsx")
df14 = pd.read_excel("../data/raw_data/total_productivity_lossess_due_to_5_oral_diseases.xlsx")

In [5]:
df1.head(2)

,Applied filters:\nLocation type is Country\nLANGUAGE_CODE is en\nIndicatorCode is ORALHEALTH_DENTALHEALTHCARE_EXP_TOTAL,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified

In [6]:
cleaned_dfs = {}

for i in range(1, 15):
    df = globals()[f'df{i}']  
    new_columns = df.iloc[1]
    df_cleaned = df.iloc[2:].copy()
    df_cleaned.columns = new_columns
    df_cleaned.reset_index(drop=True, inplace=True)
    
    # Sowohl dem Wörterbuch hinzufügen als auch den Originalnamen aktualisieren
    cleaned_dfs[f'df{i}'] = df_cleaned
    globals()[f'df{i}'] = df_cleaned

In [7]:
df1.shape

(192, 34)

In [8]:
df1.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_DENTALHEALTHCARE_EXP_TOTAL,Total expenditure on dental healthcare in mill...,numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,70.2,NaN,NaN,EN,2023-04-20 00:00:00
1,ORALHEALTH_DENTALHEALTHCARE_EXP_TOTAL,Total expenditure on dental healthcare in mill...,numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,1.3,NaN,NaN,EN,2023-04-20 00:00:00

In [9]:
for i in range(1, 15):
    print(f'df{i}: {globals()[f"df{i}"].shape}', end=' || ')

df1: (192, 34) || df2: (77, 34) || df3: (192, 34) || df4: (194, 34) || df5: (194, 34) || df6: (194, 34) || df7: (177, 34) || df8: (77, 34) || df9: (496, 34) || df10: (96, 34) || df11: (3105, 34) || df12: (519, 34) || df13: (194, 34) || df14: (192, 34) ||

In [10]:
df2.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_FLUORIDETOOTHPHASTE_LABOURDAYS,Number of labour days needed to buy annual sup...,numeric,AFR,Africa,Country,BEN,Benin,Year,2019,...,NaN,NaN,NaN,NaN,NaN,11.8,NaN,NaN,EN,2023-04-20 00:00:00
1,ORALHEALTH_FLUORIDETOOTHPHASTE_LABOURDAYS,Number of labour days needed to buy annual sup...,numeric,AFR,Africa,Country,BFA,Burkina Faso,Year,2019,...,NaN,NaN,NaN,NaN,NaN,2.7,NaN,NaN,EN,2023-04-20 00:00:00

In [11]:
df3.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_DENTALHEALTHCARE_EXP_PERCAP,Per capita expenditure on dental healthcare (US$),numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,2.3,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_DENTALHEALTHCARE_EXP_PERCAP,Per capita expenditure on dental healthcare (US$),numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,EN,2023-04-17 00:00:00

In [12]:
df4.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_EDENTULISM_PREVALENCE,Prevalence of edentulism in people 20+ years (%),numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_EDENTULISM_PREVALENCE,Prevalence of edentulism in people 20+ years (%),numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,EN,2023-04-17 00:00:00

In [13]:
df5.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_SEVEREPERIODONTALDISEASE,Prevalence of severe periodontal disease in pe...,numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,23.9,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_SEVEREPERIODONTALDISEASE,Prevalence of severe periodontal disease in pe...,numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,19.2,NaN,NaN,EN,2023-04-17 00:00:00

In [14]:
df6.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_UNTREATEDCARIESPERMANENT,Prevalence of untreated caries of permanent te...,numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,27.2,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_UNTREATEDCARIESPERMANENT,Prevalence of untreated caries of permanent te...,numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,31.7,NaN,NaN,EN,2023-04-17 00:00:00

In [15]:
df7.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_AVAILABILITY_URGENTCARE,Oral health: Urgent treatment for providing em...,text,AFR,Africa,Country,AGO,Angola,Year,2021,...,NaN,NaN,NaN,NaN,NaN,Unavailable,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_AVAILABILITY_URGENTCARE,Oral health: Urgent treatment for providing em...,text,AFR,Africa,Country,BDI,Burundi,Year,2021,...,NaN,NaN,NaN,NaN,NaN,Unavailable,NaN,NaN,EN,2023-04-17 00:00:00

In [16]:
df7["Period"].value_counts()

Period
2021    177
Name: count, dtype: int64

In [17]:
df8.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_AFFORDABILITY_FLUORIDETOOTHPASTE,Affordability of fluoride toothpaste,text,AFR,Africa,Country,BEN,Benin,Year,2019,...,NaN,NaN,NaN,NaN,NaN,Unaffordable,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_AFFORDABILITY_FLUORIDETOOTHPASTE,Affordability of fluoride toothpaste,text,AFR,Africa,Country,BFA,Burkina Faso,Year,2019,...,NaN,NaN,NaN,NaN,NaN,Unaffordable,NaN,NaN,EN,2023-04-17 00:00:00

In [18]:
df9.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,HWF_0012,Dental Assistants and Therapists (number),numeric,AFR,Africa,Country,AGO,Angola,Year,2022,...,NaN,NaN,NaN,NaN,NaN,796,NaN,"NHWA data portal, December 2024 update https:/...",EN,2025-01-14 00:00:00
1,HWF_0012,Dental Assistants and Therapists (number),numeric,AFR,Africa,Country,BEN,Benin,Year,2022,...,NaN,NaN,NaN,NaN,NaN,7,NaN,"NHWA data portal, December 2024 update https:/...",EN,2025-01-14 00:00:00

In [19]:
df9["Period"].value_counts()

Period
2019    63
2022    51
2018    46
2020    39
2021    37
2023    29
2004    24
2017    22
2016    18
2008    16
2015    15
2010    14
2009    14
2014    12
2012    12
2011    11
2007     9
2013     8
2002     7
2006     6
2001     5
2005     5
2000     5
2003     3
1995     3
1992     2
1997     2
1991     2
1988     2
1998     2
1996     2
1987     1
1984     1
1985     1
1986     1
1994     1
1989     1
1990     1
1993     1
1999     1
1983     1
Name: count, dtype: int64

In [20]:
df10.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_HWF_DENTALPROSTHETICTECH_10K,Dental prosthetic technicians (per 10 000 popu...,numeric,AFR,Africa,Country,BEN,Benin,Year,2014-2019,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2023-04-20 00:00:00
1,ORALHEALTH_HWF_DENTALPROSTHETICTECH_10K,Dental prosthetic technicians (per 10 000 popu...,numeric,AFR,Africa,Country,BFA,Burkina Faso,Year,2014-2019,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2023-04-20 00:00:00

In [21]:
df10["Period"].value_counts()

Period
2014-2019    96
Name: count, dtype: int64

In [22]:
df11.head(3)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,HWF_0010,"Dentists (per 10,000)",numeric,AFR,Africa,Country,AGO,Angola,Year,2022,...,NaN,NaN,NaN,NaN,NaN,0.07,NaN,"NHWA data portal, December 2024 update https:/...",EN,2025-01-14 00:00:00
1,HWF_0010,"Dentists (per 10,000)",numeric,AFR,Africa,Country,AGO,Angola,Year,2018,...,NaN,NaN,NaN,NaN,NaN,0.53,NaN,"NHWA data portal, December 2024 update https:/...",EN,2025-01-14 00:00:00
2,HWF_0010,"Dentists (per 10,000)",numeric,AFR,Africa,Country,AGO,Angola,Year,2004,...,NaN,NaN,NaN,NaN,NaN,0.12,NaN,"NHWA data portal, December 2024 update https:/...",EN,2025-01-14 00:00:00

In [23]:
df11["Period"].dtype

dtype('O')

In [24]:
(df11['Period'] == "2019").sum()

129

In [25]:
df12.head(10)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,...,NaN,NaN,NaN,NaN,NaN,482,NaN,NaN,EN,2023-04-20 00:00:00
1,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,...,NaN,NaN,NaN,NaN,NaN,316,NaN,NaN,EN,2023-04-20 00:00:00
2,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,...,NaN,NaN,NaN,NaN,NaN,166,NaN,NaN,EN,2023-04-20 00:00:00
3,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BDI,Burundi,Year,2020,...,NaN,NaN,NaN,NaN,NaN,92,NaN,NaN,EN,2023-04-20 00:00:00
4,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BDI,Burundi,Year,2020,...,NaN,NaN,NaN,NaN,NaN,62,NaN,NaN,EN,2023-04-20 00:00:00
5,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BDI,Burundi,Year,2020,...,NaN,NaN,NaN,NaN,NaN,30,NaN,NaN,EN,2023-04-20 00:00:00
6,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BEN,Benin,Year,2020,...,NaN,NaN,NaN,NaN,NaN,74,NaN,NaN,EN,2023-04-20 00:00:00
7,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BEN,Benin,Year,2020,...,NaN,NaN,NaN,NaN,NaN,32,NaN,NaN,EN,2023-04-20 00:00:00
8,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BEN,Benin,Year,2020,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,EN,2023-04-20 00:00:00
9,ORAL_HEALTH_CANCER_LIPORALCAVITY_NEWCASE_NUMBER,Number of new cases of lip and oral cavity cancer,numeric,AFR,Africa,Country,BFA,Burkina Faso,Year,2020,...,NaN,NaN,NaN,NaN,NaN,179,NaN,NaN,EN,2023-04-20 00:00:00

In [26]:
df12["label"] =  df12.groupby("Location").cumcount().map({0: "TotalCancerNewCases", 1: "MaleCancerNewCases", 2: "FemaleCancerNewCases"})

df_wide= df12.pivot(index= "Location", columns= "label", values= "Value").reset_index()

df_wide.columns.name= None

df_wide.head()

      Location FemaleCancerNewCases MaleCancerNewCases TotalCancerNewCases
0  Afghanistan                  295                618                 913
1      Albania                   48                 58                 106
2      Algeria                  107                186                 293
3       Angola                  166                316                 482
4    Argentina                  414                890               1 304

In [27]:
df13.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_UNTREATEDCARIESDECIDUOUS,Prevalence of untreated caries of deciduous te...,numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,37.8,NaN,NaN,EN,2023-04-17 00:00:00
1,ORALHEALTH_UNTREATEDCARIESDECIDUOUS,Prevalence of untreated caries of deciduous te...,numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,41.6,NaN,NaN,EN,2023-04-17 00:00:00

In [28]:
df14.head(2)

1,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,ORALHEALTH_PRODLOSS_ORALDISEASES,Total productivity losses due to 5 oral diseas...,numeric,AFR,Africa,Country,AGO,Angola,Year,2019,...,NaN,NaN,NaN,NaN,NaN,195.8,NaN,NaN,EN,2023-04-20 00:00:00
1,ORALHEALTH_PRODLOSS_ORALDISEASES,Total productivity losses due to 5 oral diseas...,numeric,AFR,Africa,Country,BDI,Burundi,Year,2019,...,NaN,NaN,NaN,NaN,NaN,5.3,NaN,NaN,EN,2023-04-20 00:00:00

In [29]:
df1_renamed = df1[['Location', 'Period', 'Value']].rename(columns={'Value': 'TotalExpenditure'})
df3_renamed = df3[['Location', 'Period', 'Value']].rename(columns={'Value': 'PerCapitaExpenditure'})
df4_renamed = df4[['Location', 'Period', 'Value']].rename(columns={'Value': 'EdentulismRate'})
df5_renamed = df5[['Location', 'Period', 'Value']].rename(columns={'Value': 'PeriodontalRate'})
df6_renamed = df6[['Location', 'Period', 'Value']].rename(columns={'Value': 'UntreatedCariesRate'})
df13_renamed = df13[['Location', 'Period', 'Value']].rename(columns={'Value': 'UntreatedDeciduousCaries1_9Rate'})
df14_renamed = df14[['Location', 'Period', 'Value']].rename(columns={'Value': 'ProductivityLoss'})


merged_df = df1_renamed.merge(df3_renamed, on=['Location', 'Period'])
merged_df = merged_df.merge(df4_renamed, on=['Location', 'Period'])
merged_df = merged_df.merge(df5_renamed, on=['Location', 'Period'])
merged_df = merged_df.merge(df6_renamed, on=['Location', 'Period'])
merged_df = merged_df.merge(df13_renamed, on=['Location', 'Period'])
merged_df = merged_df.merge(df14_renamed, on=['Location', 'Period'])

merged_df = merged_df.merge(df_wide, on='Location', how='left')

In [30]:
merged_df.head()

,Location,Period,TotalExpenditure,PerCapitaExpenditure,EdentulismRate,PeriodontalRate,UntreatedCariesRate,UntreatedDeciduousCaries1_9Rate,ProductivityLoss,FemaleCancerNewCases,MaleCancerNewCases,TotalCancerNewCases
0,Angola,2019,70.2,2.3,4.0,23.9,27.2,37.8,195.8,166,316,482
1,Burundi,2019,1.3,0.1,2.0,19.2,31.7,41.6,5.3,30,62,92
2,Benin,2019,3.3,0.3,2.9,27.1,29.5,39.6,30.0,42,32,74
3,Burkina Faso,2019,4.6,0.2,1.9,27.4,27.5,40.3,30.8,55,124,179
4,Botswana,2019,57.4,24.1,7.5,26.3,32.7,37.6,59.2,8,52,60

In [31]:
merged_df.shape

(192, 12)

In [32]:
#merged_df.to_excel("agizsagligi.xlsx", index=False)

In [33]:
merged_df.columns

Index(['Location', 'Period', 'TotalExpenditure', 'PerCapitaExpenditure',
       'EdentulismRate', 'PeriodontalRate', 'UntreatedCariesRate',
       'UntreatedDeciduousCaries1_9Rate', 'ProductivityLoss',
       'FemaleCancerNewCases', 'MaleCancerNewCases', 'TotalCancerNewCases'],
      dtype='object')